//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BknDal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateObjectPhoto
    {
        public long RealEstateObjectPhotoId { get; set; }
        public long RealEstateObjectId { get; set; }
        public string Url { get; set; }
        public string Md5 { get; set; }
        public Nullable<bool> isPrimary { get; set; }
    
        public virtual RealEstateObject RealEstateObject { get; set; }
    }
}
